### ISSUE TITLE
TypeError: '<' not supported between instances of 'str' and 'int'

### ISSUE THREAD

**Issue by camAtGitHub** [ilyash/show-struct#11]
Hello,
Firstly thanks for the script - I find it very useful hence the request :-)

Given an input of:
`{"ansible_python":{"version":{"major":2,"micro":5,"minor":7,"releaselevel":"final","serial":0},"version_info":[2,7,5,"final",0]}}`

Is it possible to work around the type comparison being done in this instance?

Many Thanks

**Comment by aclarknexient** [comment]
I'm also seeing this issue. I wish I could help fix it!

**Comment by camAtGitHub** [comment]
@aclarknexient try https://github.com/tomnomnom/gron/ it works pretty good

**Comment by aclarknexient** [comment]
Thank you for the `gron` recommendation, it's really great!
